### ISSUE TITLE
google-doc says "This document was last updated on February 5, 2023" but github last updated 2022-09-22 as of today 2024-12-21

### ISSUE THREAD

**Issue by porteusconf** [ggodreau/volt#1]
Thank you for putting on github, and I'll try to contribute. For example, I did notice that the google-doc has some info not in this git repo, including this line just before: step 1:
>  "This document was last updated on February 5, 2023"

But I saw no way to have google-docs tell me what was updated. So I put them up side by side and by eye noticed the google-doc had added the following line in the middle of step 12:

>			This is where the VIN assignment to your subscription happens. You will see a message that says "Warning: The current vehicle will take one of your available VIN Slots." Simply select the “Proceed” button and your ACDelco subscription will be updated.

Finally, thanks again for additions that appear on github but not in the google-doc, such as:
>		Note: Techline Connect will still work even if your PC doesn’t meet their required specifications

In general, it is pain to read thru pages of advertising-laden postings at [https://www.gm-volt.com/](https://www.gm-volt.com/) or reddit. When important info is presented, I see folks saying this should be more easily found, perhaps by making a "sticky" post (tho I don't see how or where to make something sticky other than to bookmark it). And while I think it is good idea to use something like github to track changes and keep info up-to-date, I'm playing with some more user-friendly methods more akin to wikipedia. I'll report back here and the forum/reddit when I have something concrete to suggest.  BTW, I'm having to do this procedure for the second time in under 2 years... ordered the defeat plug this time ;-)

**Comment by ggodreau** [comment]
Tks @porteusconf for the heads up; updated step 12 - please check out the PR and lmk if that looks right 👍🏿
